run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - bodyclose
    - gosec

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"

issues:
  exclude-dirs:
    - bin
    - dist
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
